config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    patch 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  root 'static_pages#statistics'

  concern :networkable do
    resources :network_interfaces, except: [:index, :show], shallow: true
  end

  get 'settings',   to: 'static_pages#settings',   as: 'settings'
  get 'statistics', to: 'static_pages#statistics', as: 'statistics'

  resources :adonis,  concerns: :networkable
  resources :proteus, concerns: :networkable

  resources :locations
  resources :models,   except: [:index, :show]
  resources :statuses, except: [:index, :show]
  resources :users,    only: [:create, :destroy, :index, :new]
  resources :xha,      except: :index, concerns: :networkable
end

app/controllers/static_pages_controller.rb
# The StaticPagesController does not control the interaction with resources, but instead provides a central
# management point to deliver static pages.
class StaticPagesController < ApplicationController
  def settings
    @models = Model.all
    @statuses = Status.all
  end

  def statistics
    @adonis_count = Adonis.count
    @proteus_count = Proteus.count

    @user_count = User.count

    @models = Model.all
    @statuses = Status.all
  end
end

app/views/static_pages/settings.html.erb
<% provide :title, t('views.static_pages.settings.title') %>

<article>
  <h1><%= t 'views.static_pages.settings.title' %></h1>
  <p><%= t 'views.static_pages.settings.description' %></p>

  <h3><%= t 'models.adonis.model' %></h3>
  <p><%= t 'views.static_pages.settings.models' %></p>

  <table class="tables">
    <thead>
    <tr>
      <th><%= t 'models.models.name' %></th>
      <th><%= t 'models.models.eol' %></th>
      <th><%= t 'views.application.options' %></th>
    </tr>
    </thead>
    <tbody>
    <% @models.each do |model| %>
        <tr>
          <td><%= model.name %></td>
          <td><%= model.eol %></td>
          <td>
            <%= link_to edit_model_path(model), class: 'button' do %>
                <%= t 'views.application.buttons.edit' %>
            <% end %>
            <%= link_to t('views.application.buttons.delete'), model_path(model),
                        data: { confirm: t('views.application.confirm_delete',
                                   resource: t('models.adonis.model').downcase,
                                   identifier: model.name) },
                        method: :delete, class: 'button-delete' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <p><%= link_to t('views.application.create', resource: 'model'), new_model_path, class: 'button' %></p>

  <h3><%= t 'models.adonis.status' %></h3>
  <p><%= t 'views.static_pages.settings.statuses' %></p>

  <table class="tables">
    <thead>
    <tr>
      <th><%= t 'models.statuses.name' %></th>
      <th><%= t 'views.application.options' %></th>
    </tr>
    </thead>
    <tbody>
    <% @statuses.each do |status| %>
        <tr>
          <td><%= status.name %></td>
          <td>
            <%= link_to edit_status_path(status), class: 'button' do %>
                <%= t 'views.application.buttons.edit' %>
            <% end %>
            <%= link_to t('views.application.buttons.delete'), status_path(status),
                        data: { confirm: t('views.application.confirm_delete',
                                   resource: t('models.adonis.status').downcase,
                                   identifier: status.name) },
                        method: :delete, class: 'button-delete' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <p><%= link_to t('views.application.create', resource: 'status'), new_status_path, class: 'button' %></p>
</article>

app/views/static_pages/statistics.html.erb
<% provide :title, t('views.static_pages.statistics.title') %>

<article>
  <h1><%= t 'views.static_pages.statistics.title' %></h1>
  <p><%= t 'views.static_pages.statistics.description' %></p>

  <h3><%= t 'views.static_pages.statistics.resources' %></h3>
  <table class="tables">
    <thead>
    <tr>
      <th># Adonis</th>
      <th># Proteus</th>
      <th># <%= t 'views.application.user' %></th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= link_to @adonis_count, adonis_index_path %></td>
      <td><%= link_to @proteus_count, proteus_index_path %></td>
      <td><%= link_to @user_count, users_path %></td>
    </tr>
    </tbody>
  </table>

  <h3><%= t 'views.static_pages.statistics.models' %></h3>
  <table class="tables">
    <thead>
    <th><%= t 'models.adonis.model' %></th>
    <th># Adonis</th>
    <th># Proteus</th>
    </thead>
    <tbody>
    <% @models.each do |model| %>
        <tr>
          <td><%= model.name %></td>
          <td>
            <% unless model.adonis.count == 0 || @adonis_count == 0 %>
                <%= link_to adonis_index_path(model_id: model.id) do %>
                    <div class="progress-bar-indication">
                      <span class="meter" style="width: <%= model.adonis.count * 100 / @adonis_count %>%">
                        <p><%= model.adonis.count %></p>
                      </span>
                    </div>
                <% end %>
            <% end %>
          </td>
          <td>
            <% unless model.proteus.count == 0 || @proteus_count == 0 %>
                <%= link_to proteus_index_path(model_id: model.id) do %>
                    <div class="progress-bar-indication">
                      <span class="meter" style="width: <%= model.proteus.count * 100 / @proteus_count %>%">
                        <p><%= model.proteus.count %></p>
                      </span>
                    </div>
                <% end %>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <h3><%= t 'views.static_pages.statistics.statuses' %></h3>
  <table class="tables">
    <thead>
    <th><%= t 'models.adonis.status' %></th>
    <th># Adonis</th>
    <th># Proteus</th>
    </thead>
    <tbody>
    <% @statuses.each do |status| %>
        <tr>
          <td><%= status.name %></td>
          <td>
            <% unless status.adonis.count == 0 || @adonis_count == 0 %>
                <%= link_to adonis_index_path(status_id: status.id) do %>
                    <div class="progress-bar-indication">
                      <span class="meter" style="width: <%= status.adonis.count * 100 / @adonis_count %>%">
                        <p><%= status.adonis.count %></p>
                      </span>
                    </div>
                <% end %>
            <% end %>
          </td>
          <td>
            <% unless status.proteus.count == 0 || @proteus_count == 0 %>
                <%= link_to proteus_index_path(status_id: status.id) do %>
                    <div class="progress-bar-indication">
                      <span class="meter" style="width: <%= status.proteus.count * 100 / @proteus_count %>%">
                        <p><%= status.proteus.count %></p>
                      </span>
                    </div>
                <% end %>
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</article>