config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    patch 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  root 'static_pages#statistics'

  concern :networkable do
    resources :network_interfaces, except: [:index, :show], shallow: true
  end

  get 'settings',   to: 'static_pages#settings',   as: 'settings'
  get 'statistics', to: 'static_pages#statistics', as: 'statistics'

  resources :adonis,  concerns: :networkable
  resources :proteus, concerns: :networkable

  resources :locations
  resources :models,   except: [:index, :show]
  resources :statuses, except: [:index, :show]
  resources :users,    only: [:create, :destroy, :index, :new]
  resources :xha,      except: :index, concerns: :networkable
end

app/models/adonis.rb
require 'ipaddress'

# Adonis are BlueCat Network's DHCP/DNS server, and are typically the most common server type. Adonis are identified
# by both an hostname and an identifier, both of which must be unique. While the hostname should be pretty
# self-explanatory, the identifier can be used to assign a unique name to a server for internal referencing.
# Depending on your organization, it can be the same as either the hostname, or the serial or inventory number.
#
# The serial number is assigned to a server by BlueCat, and is useful for service requests or hardware replacements.
# The inventory number is typically assigned to a server by your organization, and is optional.
# Three password fields exist, one for the root account, the admin account and one for the deploy account.
# The field 'Syslog server' contains the IP address of the Adonis' primary Syslog server.
# The SNMP community can be set if SNMPv1 or SNMPv2c is used.
class Adonis < ActiveRecord::Base
  include Filterable

  scope :location_id, -> (location_id) { where location_id: location_id }
  scope :model_id, -> (model_id) { where model_id: model_id }
  scope :status_id, -> (status_id) { where status_id: status_id }

  HOSTNAME_REGEX = /\A[a-z0-9\-\.]*\z/i
  IDENTIFIER_REGEX = /\A.*\z/i

  validates :hostname,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: HOSTNAME_REGEX }
  validates :identifier,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: IDENTIFIER_REGEX }
  validates :root_password,
            presence: true

  validate :ipv4_gateway_has_valid_format, :ipv6_gateway_has_valid_format, :syslog_server_has_valid_format

  belongs_to :location, inverse_of: :adonis
  belongs_to :model, inverse_of: :adonis
  belongs_to :status, inverse_of: :adonis

  has_many :network_interfaces, as: :networkable, inverse_of: :networkable, dependent: :destroy

  before_save do
    hostname.downcase!
    identifier.upcase!
  end

  def xha
    XHA.where('master_id = ? OR slave_id = ?', id, id).first
  end

  private

  def ipv4_gateway_has_valid_format
    return if ipv4_gateway.blank? || IPAddress.valid_ipv4?(ipv4_gateway)
    errors.add :ipv4_gateway, I18n.t('models.application.invalid_format',
                                     attribute: I18n.t('models.adonis.ipv4_gateway'),
                                     expected: '192.168.1.1')
  end

  def ipv6_gateway_has_valid_format
    return if ipv6_gateway.blank? || IPAddress.valid_ipv6?(ipv6_gateway)
    errors.add :ipv6_gateway, I18n.t('models.application.invalid_format',
                                     attribute: I18n.t('models.adonis.ipv6_gateway'),
                                     expected: 'ac5f:d696:3807:1d72::7d2b:e1df')
  end

  def syslog_server_has_valid_format
    return if syslog_server.blank? || IPAddress.valid_ipv4?(syslog_server)
    errors.add :syslog_server, I18n.t('models.application.invalid_format',
                                      attribute: I18n.t('models.adonis.syslog_server'),
                                      expected: '192.168.1.1')
  end
end

app/controllers/adonis_controller.rb
# This controller controls the interaction with Adonis servers. It has the default actions every Rails controller
# has: index, show, edit, update, new, create.
class AdonisController < ApplicationController
  def create
    @adonis = Adonis.new adonis_params

    if @adonis.save
      flash[:success] = t 'controllers.application.create.successful', resource: 'Adonis'
      redirect_to adonis_path @adonis
    else
      flash[:error] = @adonis.errors.full_messages
      render :new
    end
  end

  def destroy
    @adonis = Adonis.find_by_id params[:id]
    return redirect_adonis_not_found unless @adonis

    if @adonis.destroy
      flash[:success] = t 'controllers.application.destroy.successful', resource: 'Adonis'
      redirect_to adonis_index_path
    else
      flash[:error] = @adonis.errors.full_messages
      redirect_to adonis_path @adonis
    end
  end

  def edit
    @adonis = Adonis.find_by_id params[:id]
    redirect_adonis_not_found unless @adonis
  end

  def index
    @adonis = Adonis.filter(params.slice(:model_id, :location_id, :status_id))
  end

  def new
  end

  def show
    @adonis = Adonis.find_by_id params[:id]
    redirect_adonis_not_found unless @adonis
  end

  def update
    @adonis = Adonis.find_by_id params[:id]
    return redirect_adonis_not_found unless @adonis

    if @adonis.update_attributes adonis_params
      flash[:success] = t 'controllers.application.update.successful', identifier: @adonis.hostname
      redirect_to adonis_path @adonis
    else
      flash[:error] = @adonis.errors.full_messages
      redirect_to edit_adonis_path @adonis
    end
  end

  private

  def adonis_params
    params.require(:adonis).permit(:admin_password, :deploy_password, :hostname, :identifier, :inventory_number,
                                   :ipv4_gateway, :ipv6_gateway, :location_id, :model_id, :root_password,
                                   :serial_number, :status_id)
  end

  def redirect_adonis_not_found
    flash[:error] = t 'controllers.application.access.not_found', resource: 'Adonis'
    redirect_to adonis_index_path
  end
end

app/views/adonis/_form.html.erb
<%= form_for adonis ||= Adonis.new do |f| %>
    <% if adonis.id %>
        <%= f.label :id %>
        <%= f.text_field :id, disabled: true %>
    <% end %>

    <%= f.label :hostname %>
    <%= f.text_field :hostname %>

    <%= f.label :identifier %>
    <%= f.text_field :identifier %>

    <%= f.label :inventory_number %>
    <%= f.text_field :inventory_number %>

    <%= f.label :model %>
    <%= f.select :model_id,
                 options_from_collection_for_select(Model.all, 'id', 'name', adonis.model ? adonis.model.id : nil),
                 include_blank: true %>

    <%= f.label :status %>
    <%= f.select :status_id,
                 options_from_collection_for_select(Status.all, 'id', 'name', adonis.status ? adonis.status.id : nil),
                 include_blank: true %>

    <%= f.label :location %>
    <%= f.select :location_id,
                 options_from_collection_for_select(Location.all, 'id', 'name', adonis.location ? adonis.location
                                                                          .id : nil),
                 include_blank: true %>

    <%= f.label :ipv4_gateway %>
    <%= f.text_field :ipv4_gateway %>

    <%= f.label :ipv6_gateway %>
    <%= f.text_field :ipv6_gateway %>

    <%= f.label :root_password %>
    <%= f.text_field :root_password %>

    <%= f.label :admin_password %>
    <%= f.text_field :admin_password %>

    <%= f.label :deploy_password %>
    <%= f.text_field :deploy_password %>

    <%= f.label :snmp_community %>
    <%= f.text_field :snmp_community %>

    <%= f.label :syslog_server %>
    <%= f.text_field :syslog_server %>

    <%= f.submit t 'views.application.buttons.save' %>
<% end %>

app/views/adonis/_table.html.erb
<table class="tables">
  <thead>
  <tr>
    <th><%= t 'models.adonis.hostname' %></th>
    <th><%= t 'models.adonis.location' %></th>
    <th><%= t 'models.adonis.status' %></th>
    <th><%= t 'models.adonis.root_password' %></th>
    <th><%= t 'models.adonis.identifier' %></th>
  </tr>
  </thead>
  <tbody>
  <% adonis.each do |a| %>
      <tr>
        <td><%= link_to a.hostname, adonis_path(a) %></td>
        <td>
          <% if a.location.present? %>
            <%= link_to a.location.name, adonis_index_path(location_id: a.location.id) %>
          <% end %>
        </td>
        <td>
          <% if a.status.present? %>
              <%= link_to a.status.name, adonis_index_path(status_id: a.status.id) %>
          <% end %>
        </td>
        <td><%= a.root_password %></td>
        <td><%= link_to a.identifier, adonis_path(a) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/adonis/edit.html.erb
<% provide :title, t('views.application.edit', resource: @adonis.hostname) %>

<article>
  <h1><%= t 'views.application.edit', resource: @adonis.hostname %></h1>
  <%= render 'adonis/form', adonis: @adonis %>
</article>

app/views/adonis/index.html.erb
<article>
  <h1>Adonis</h1>
  <p><%= t 'views.adonis.index.description' %></p>

  <p><%= link_to t('views.application.create', resource: 'Adonis'), new_adonis_path, class: 'button' %></p>

  <%= render 'adonis/table', adonis: @adonis %>
</article>

app/views/adonis/new.html.erb
<% provide :title, t('views.application.create', resource: 'Adonis') %>

<article>
  <h1><%= t 'views.application.create', resource: 'Adonis' %></h1>
  <%= render 'adonis/form' %>
</article>

app/views/adonis/show.html.erb
<% provide :title, @adonis.hostname %>

<article>
  <h1><%= @adonis.hostname %></h1>
  <p>
    <%= link_to t('views.application.edit', resource: 'Adonis'), edit_adonis_path(@adonis), class: 'button' %>
    <%= link_to t('views.application.delete', resource: 'Adonis'),
                adonis_path(@adonis), confirm: t('views.adonis.show.confirm_delete', hostname: @adonis.hostname),
                method: :delete, class: 'button-delete' %>
  </p>

  <h3><%= t 'models.adonis.network_interfaces' %></h3>
  <% if @adonis.network_interfaces.empty? %>
      <div class="flash-notice">
        <span>
          <%= t 'views.adonis.show.no_network_interfaces' %>
          <%= link_to new_adonis_network_interface_path @adonis do %>
            <%= t('views.application.create', resource: 'network interface') %>
          <% end %>
        </span>
      </div>
  <% else %>
      <table class="tables" style="table-layout: auto">
        <thead>
        <tr>
          <th><%= t 'models.network_interfaces.name' %></th>
          <th><%= t 'models.network_interfaces.mac_address' %></th>
          <th><%= t 'models.network_interfaces.ipv4_address' %></th>
          <th><%= t 'models.network_interfaces.ipv6_address' %></th>
          <th><%= t 'views.application.options' %></th>
        </tr>
        </thead>
        <tbody>
        <% @adonis.network_interfaces.each do |interface| %>
            <tr>
              <td><%= interface.name %></td>
              <td><%= interface.mac_address %></td>
              <td>
                <% if interface.ipv4_address.present? %>
                    <%= interface.ipv4_address %> (<%= interface.ipv4_netmask%>)
                <% end %>
              </td>
              <td>
                <% if interface.ipv6_address.present? %>
                    <%= interface.ipv6_address %> / <%= interface.ipv6_prefix %>
                <% end %>
              </td>
              <td>
                <%= link_to edit_network_interface_path(interface), class: 'button' do %>
                    <%= t 'views.application.buttons.edit' %>
                <% end %>
                <%= link_to t('views.application.buttons.delete'), network_interface_path(interface),
                            confirm: t('views.application.confirm_delete',
                                       resource: t('models.adonis.network_interface').downcase,
                                       identifier: interface.name),
                            method: :delete, class: 'button-delete' %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <p>
        <%= link_to new_adonis_network_interface_path(@adonis), class: 'button' do %>
            <%= t 'views.application.create', resource: t('models.adonis.network_interface') %>
        <% end %>
      </p>
  <% end %>

  <h3>XHA</h3>
  <% if @adonis.xha.nil? %>
      <div class="flash-notice">
        <span>
          <%= t 'views.adonis.show.no_xha' %>
          <%= link_to new_xha_path do %>
            <%= t('views.application.create', resource: 'XHA') %>
          <% end %>
        </span>
      </div>
  <% else %>
      <table class="tables">
        <thead>
        <tr>
          <th><%= t 'models.xha.master' %></th>
          <th><%= t 'models.xha.slave' %></th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td><%= link_to @adonis.xha.master.hostname, adonis_path(@adonis.xha.master) %></td>
          <td><%= link_to @adonis.xha.slave.hostname, adonis_path(@adonis.xha.slave) %></td>
        </tr>
        </tbody>
      </table>

      <p>
        <%= link_to edit_xha_path(@adonis.xha), class: 'button' do %>
            <%= t 'views.application.buttons.replace' %>
        <% end %>
        <%= link_to t('views.application.delete', resource: 'XHA'), xha_path(@adonis.xha),
                    data: { confirm: t('views.application.confirm_delete', resource: 'XHA',
                                                      identifier: @adonis.xha.id) },
                    method: :delete, class: 'button-delete' %>
      </p>

      <table class="tables" style="table-layout: auto">
        <thead>
        <tr>
          <th><%= t 'models.network_interfaces.name' %></th>
          <th><%= t 'models.network_interfaces.mac_address' %></th>
          <th><%= t 'models.network_interfaces.ipv4_address' %></th>
          <th><%= t 'models.network_interfaces.ipv6_address' %></th>
          <th><%= t 'views.application.options' %></th>
        </tr>
        </thead>
        <tbody>
        <% @adonis.xha.network_interfaces.each do |interface| %>
            <tr>
              <td><%= interface.name %></td>
              <td><%= interface.mac_address %></td>
              <td>
                <% if interface.ipv4_address.present? %>
                    <%= interface.ipv4_address %> (<%= interface.ipv4_netmask%>)
                <% end %>
              </td>
              <td>
                <% if interface.ipv6_address.present? %>
                    <%= interface.ipv6_address %> / <%= interface.ipv6_prefix %>
                <% end %>
              </td>
              <td>
                <%= link_to edit_network_interface_path(interface), class: 'button' do %>
                    <%= t 'views.application.buttons.edit' %>
                <% end %>
                <%= link_to t('views.application.buttons.delete'), network_interface_path(interface),
                            data: { confirm: t('views.application.confirm_delete',
                                       resource: t('models.adonis.network_interface').downcase,
                                       identifier: interface.name) },
                            method: :delete, class: 'button-delete' %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <p>
        <%= link_to new_xha_network_interface_path(@adonis.xha), class: 'button' do %>
            <%= t 'views.application.create', resource: t('models.adonis.network_interface') %>
        <% end %>
      </p>
  <% end %>

  <h3>Gateways</h3>
  <table class="tables">
    <thead>
    <tr>
      <th><%= t 'models.adonis.ipv4_gateway' %></th>
      <th><%= t 'models.adonis.ipv6_gateway' %></th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= @adonis.ipv4_gateway %></td>
      <td><%= @adonis.ipv6_gateway %></td>
    </tr>
    </tbody>
  </table>

  <h3><%= t 'views.application.passwords' %></h3>
  <table class="tables">
    <thead>
    <tr>
      <th><%= t 'models.adonis.root_password' %></th>
      <th><%= t 'models.adonis.admin_password' %></th>
      <th><%= t 'models.adonis.deploy_password' %></th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= @adonis.root_password %></td>
      <td><%= @adonis.admin_password %></td>
      <td><%= @adonis.deploy_password %></td>
    </tr>
    </tbody>
  </table>

  <h3><%= t 'views.application.details' %></h3>
  <table class="tables">
    <thead>
    <tr>
      <th><%= t 'views.application.key' %></th>
      <th><%= t 'views.application.value' %></th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>ID</td>
      <td><%= @adonis.id %></td>
    </tr>
    <tr>
      <td><%= t 'models.adonis.identifier' %></td>
      <td><%= @adonis.identifier %></td>
    </tr>
    <tr>
      <td><%= t 'models.adonis.inventory_number' %></td>
      <td><%= @adonis.inventory_number %></td>
    </tr>
    <tr>
      <td><%= t 'models.adonis.location' %></td>
      <td><%= @adonis.location.name if @adonis.location.present? %></td>
    </tr>
    <tr>
      <td><%= t 'models.adonis.model' %></td>
      <td><%= @adonis.model.name if @adonis.model.present? %></td>
    </tr>
    <tr>
      <td><%= t 'models.adonis.snmp_community' %></td>
      <td><%= @adonis.snmp_community %></td>
    </tr>
    <tr>
      <td><%= t 'models.adonis.status' %></td>
      <td><%= @adonis.status.name if @adonis.status.present? %></td>
    </tr>
    <tr>
      <td><%= t 'models.adonis.syslog_server' %></td>
      <td><%= @adonis.syslog_server %></td>
    </tr>
    <tr>
      <td><%= t 'views.application.last_updated' %></td>
      <td><%= l @adonis.updated_at, format: :long %></td>
    </tr>
    </tbody>
  </table>
</article>