config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    patch 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  root 'static_pages#statistics'

  concern :networkable do
    resources :network_interfaces, except: [:index, :show], shallow: true
  end

  get 'settings',   to: 'static_pages#settings',   as: 'settings'
  get 'statistics', to: 'static_pages#statistics', as: 'statistics'

  resources :adonis,  concerns: :networkable
  resources :proteus, concerns: :networkable

  resources :locations
  resources :models,   except: [:index, :show]
  resources :statuses, except: [:index, :show]
  resources :users,    only: [:create, :destroy, :index, :new]
  resources :xha,      except: :index, concerns: :networkable
end

app/models/proteus.rb
require 'ipaddress'

# Proteus are BlueCat Network's management servers, and provide the web interface to configure and manage Adonis
# servers. Proteus are identified by both an hostname and an identifier, both of which must be unique. While the
# hostname should be pretty self-explanatory, the identifier can be used to assign a unique name to a server for
# internal referencing. Depending on your organization, it can be the same as either the hostname, or the serial or
# inventory number.
#
# The serial number is assigned to a server by BlueCat, and is useful for service requests or hardware replacements.
# The inventory number is typically assigned to a server by your organization, and is optional. Additionally, the
# server's root password can be saved.
class Proteus < ActiveRecord::Base
  include Filterable

  scope :location_id, -> (location_id) { where location_id: location_id }
  scope :model_id, -> (model_id) { where model_id: model_id }
  scope :status_id, -> (status_id) { where status_id: status_id }

  HOSTNAME_REGEX = /\A[a-z0-9\-\.]*\z/i
  IDENTIFIER_REGEX = /\A.*\z/i

  validates :hostname,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: HOSTNAME_REGEX }
  validates :identifier,
            presence: true,
            uniqueness: { case_sensitive: false },
            format: { with: IDENTIFIER_REGEX }
  validates :root_password,
            presence: true

  validate :ipv4_gateway_has_valid_format, :ipv6_gateway_has_valid_format

  belongs_to :location, inverse_of: :proteus
  belongs_to :model,    inverse_of: :proteus
  belongs_to :status,   inverse_of: :proteus

  has_many :network_interfaces, as: :networkable, inverse_of: :networkable, dependent: :destroy

  before_save do
    hostname.downcase!
    identifier.upcase!
  end

  private

  def ipv4_gateway_has_valid_format
    return if ipv4_gateway.blank? || IPAddress.valid_ipv4?(ipv4_gateway)
    errors.add :ipv4_gateway, I18n.t('models.application.invalid_format',
                                     attribute: I18n.t('models.adonis.ipv4_gateway'),
                                     expected: '192.168.1.1')
  end

  def ipv6_gateway_has_valid_format
    return if ipv6_gateway.blank? || IPAddress.valid_ipv6?(ipv6_gateway)
    errors.add :ipv6_gateway, I18n.t('models.application.invalid_format',
                                     attribute: I18n.t('models.adonis.ipv6_gateway'),
                                     expected: 'ac5f:d696:3807:1d72::7d2b:e1df')
  end
end

app/controllers/proteus_controller.rb
# The ProteusController handles the interaction with Proteus servers. It has the default actions all Rails controller
# have.
class ProteusController < ApplicationController
  def create
    @proteus = Proteus.new proteus_params

    if @proteus.save
      flash[:success] = t 'controllers.application.create.successful', resource: 'Proteus'
      redirect_to proteus_path @proteus
    else
      flash[:error] = @proteus.errors.full_messages
      render :new
    end
  end

  def destroy
    @proteus = Proteus.find_by_id params[:id]
    return redirect_proteus_not_found unless @proteus

    if @proteus.destroy
      flash[:success] = t 'controllers.application.destroy.successful', resource: 'Proteus'
      redirect_to proteus_index_path
    else
      flash[:error] = @proteus.errors.full_messages
      redirect_to proteus_path @proteus
    end
  end

  def edit
    @proteus = Proteus.find_by_id params[:id]
    redirect_proteus_not_found unless @proteus
  end

  def index
    @proteus = Proteus.filter(params.slice(:model_id, :location_id, :status_id))
  end

  def new
  end

  def show
    @proteus = Proteus.find_by_id params[:id]
    redirect_proteus_not_found unless @proteus
  end

  def update
    @proteus = Proteus.find_by_id params[:id]
    return redirect_proteus_not_found unless @proteus

    if @proteus.update_attributes proteus_params
      flash[:success] = t 'controllers.application.update.successful', identifier: @proteus.hostname
      redirect_to proteus_path @proteus
    else
      flash[:error] = @proteus.errors.full_messages
      redirect_to edit_proteus_path @proteus
    end
  end

  private

  def proteus_params
    params.require(:proteus).permit(:hostname, :identifier, :inventory_number, :ipv4_gateway, :ipv6_gateway,
                                    :location_id, :model_id, :root_password, :serial_number, :status_id)
  end

  def redirect_proteus_not_found
    flash[:error] = t 'controllers.application.access.not_found', resource: 'Proteus'
    redirect_to proteus_index_path
  end
end

app/views/proteus/_form.html.erb
<%= form_for proteus ||= Proteus.new do |f| %>
    <% if proteus.id %>
        <%= f.label :id %>
        <%= f.text_field :id, disabled: true %>
    <% end %>

    <%= f.label :hostname %>
    <%= f.text_field :hostname %>

    <%= f.label :identifier %>
    <%= f.text_field :identifier %>

    <%= f.label :inventory_number %>
    <%= f.text_field :inventory_number %>

    <%= f.label :model %>
    <%= f.select :model_id,
                 options_from_collection_for_select(Model.all, 'id', 'name', proteus.model ? proteus.model.id : nil),
                 include_blank: true %>

    <%= f.label :status %>
    <%= f.select :status_id,
                 options_from_collection_for_select(Status.all, 'id', 'name', proteus.status ? proteus.status.id : nil),
                 include_blank: true %>

    <%= f.label :location %>
    <%= f.select :location_id,
                 options_from_collection_for_select(Location.all, 'id', 'name', proteus.location ? proteus.location
                                                                          .id : nil),
                 include_blank: true %>

    <%= f.label :ipv4_gateway %>
    <%= f.text_field :ipv4_gateway %>

    <%= f.label :ipv6_gateway %>
    <%= f.text_field :ipv6_gateway %>

    <%= f.label :root_password %>
    <%= f.text_field :root_password %>

    <%= f.submit t 'views.application.buttons.save' %>
<% end %>

app/views/proteus/_table.html.erb
<table class="tables">
  <thead>
  <tr>
    <th><%= t 'models.proteus.hostname' %></th>
    <th><%= t 'models.proteus.location' %></th>
    <th><%= t 'models.proteus.status' %></th>
    <th><%= t 'models.proteus.root_password' %></th>
    <th><%= t 'models.proteus.identifier' %></th>
  </tr>
  </thead>
  <tbody>
  <% proteus.each do |p| %>
      <tr>
        <td><%= link_to p.hostname, proteus_path(p) %></td>
        <td><%= p.location.nil? ? '' : p.location.name %></td>
        <td><%= p.status.nil? ? '' : p.status.name %></td>
        <td><%= p.root_password %></td>
        <td><%= link_to p.identifier, proteus_path(p) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/proteus/edit.html.erb
<% provide :title, t('views.application.edit', resource: @proteus.hostname) %>

<article>
  <h1><%= t 'views.application.edit', resource: @proteus.hostname %></h1>
  <%= render 'proteus/form', proteus: @proteus %>
</article>

app/views/proteus/index.html.erb
<article>
  <h1>Proteus</h1>
  <p><%= t 'views.proteus.index.description' %></p>

  <p><%= link_to t('views.application.create', resource: 'Proteus'), new_proteus_path, class: 'button' %></p>

  <%= render 'proteus/table', proteus: @proteus %>
</article>

app/views/proteus/new.html.erb
<% provide :title, t('views.application.create', resource: 'Proteus') %>

<article>
  <h1><%= t 'views.application.create', resource: 'Proteus' %></h1>
  <%= render 'proteus/form' %>
</article>

app/views/proteus/show.html.erb
<% provide :title, @proteus.hostname %>

<article>
  <h1><%= @proteus.hostname %></h1>
  <p>
    <%= link_to t('views.application.edit', resource: 'Proteus'), edit_proteus_path(@proteus), class: 'button' %>
    <%= link_to t('views.application.delete', resource: 'Proteus'),
                proteus_path(@proteus), confirm: t('views.proteus.show.confirm_delete', hostname: @proteus.hostname),
                method: :delete, class: 'button-delete' %>
  </p>

  <h3><%= t 'models.proteus.network_interfaces' %></h3>
  <% if @proteus.network_interfaces.empty? %>
      <div class="flash-notice">
        <span>
          <%= t 'views.proteus.show.no_network_interfaces' %>
          <%= link_to new_proteus_network_interface_path @proteus do %>
            <%= t('views.application.create', resource: 'network interface') %>
          <% end %>
        </span>
      </div>
  <% else %>
      <table class="tables" style="table-layout: auto;">
        <thead>
        <tr>
          <th><%= t 'models.network_interfaces.name' %></th>
          <th><%= t 'models.network_interfaces.mac_address' %></th>
          <th><%= t 'models.network_interfaces.ipv4_address' %></th>
          <th><%= t 'models.network_interfaces.ipv6_address' %></th>
          <th><%= t 'views.application.options' %></th>
        </tr>
        </thead>
        <tbody>
        <% @proteus.network_interfaces.each do |interface| %>
            <tr>
              <td><%= interface.name %></td>
              <td><%= interface.mac_address %></td>
              <td>
                <% if interface.ipv4_address.present? %>
                    <%= interface.ipv4_address %> (<%= interface.ipv4_netmask%>)
                <% end %>
              </td>
              <td>
                <% if interface.ipv6_address.present? %>
                    <%= interface.ipv6_address %> / <%= interface.ipv6_prefix %>
                <% end %>
              </td>
              <td>
                <%= link_to edit_network_interface_path(interface), class: 'button' do %>
                    <%= t 'views.application.buttons.edit' %>
                <% end %>
                <%= link_to t('views.application.buttons.delete'), network_interface_path(interface),
                            data: { confirm: t('views.application.confirm_delete',
                                       resource: t('models.proteus.network_interface').downcase,
                                       identifier: interface.name) },
                            method: :delete, class: 'button-delete' %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <p>
        <%= link_to edit_proteus_path(@proteus), class: 'button' do %>
            <%= t 'views.application.create', resource: t('models.proteus.network_interface') %>
        <% end %>
      </p>
  <% end %>

  <h3>Gateways</h3>
  <table class="tables">
    <thead>
    <tr>
      <th><%= t 'models.proteus.ipv4_gateway' %></th>
      <th><%= t 'models.proteus.ipv6_gateway' %></th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= @proteus.ipv4_gateway %></td>
      <td><%= @proteus.ipv6_gateway %></td>
    </tr>
    </tbody>
  </table>

  <h3><%= t 'views.application.passwords' %></h3>
  <table class="tables">
    <thead>
    <tr>
      <th><%= t 'models.proteus.root_password' %></th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= @proteus.root_password %></td>
    </tr>
    </tbody>
  </table>

  <h3><%= t 'views.application.details' %></h3>
  <table class="tables">
    <thead>
    <tr>
      <th><%= t 'views.application.key' %></th>
      <th><%= t 'views.application.value' %></th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>ID</td>
      <td><%= @proteus.id %></td>
    </tr>
    <tr>
      <td><%= t 'models.proteus.identifier' %></td>
      <td><%= @proteus.identifier %></td>
    </tr>
    <tr>
      <td><%= t 'models.proteus.inventory_number' %></td>
      <td><%= @proteus.inventory_number %></td>
    </tr>
    <tr>
      <td><%= t 'models.proteus.location' %></td>
      <td><%= @proteus.location.name if @proteus.location.present? %></td>
    </tr>
    <tr>
      <td><%= t 'models.proteus.model' %></td>
      <td><%= @proteus.model.name if @proteus.model.present? %></td>
    </tr>
    <tr>
      <td><%= t 'models.proteus.status' %></td>
      <td><%= @proteus.status.name if @proteus.status.present? %></td>
    </tr>
    <tr>
      <td><%= t 'views.application.last_updated' %></td>
      <td><%= l @proteus.updated_at, format: :long %></td>
    </tr>
    </tbody>
  </table>
</article>