config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: :registrations
  as :user do
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    patch 'users' => 'devise/registrations#update', as: 'user_registration'
  end

  root 'static_pages#statistics'

  concern :networkable do
    resources :network_interfaces, except: [:index, :show], shallow: true
  end

  get 'settings',   to: 'static_pages#settings',   as: 'settings'
  get 'statistics', to: 'static_pages#statistics', as: 'statistics'

  resources :adonis,  concerns: :networkable
  resources :proteus, concerns: :networkable

  resources :locations
  resources :models,   except: [:index, :show]
  resources :statuses, except: [:index, :show]
  resources :users,    only: [:create, :destroy, :index, :new]
  resources :xha,      except: :index, concerns: :networkable
end

app/views/shared/_flash.html.erb
<% flash.each do |type, messages| %>
    <% Array(messages).each do |message| %>
        <div class="flash-<%= type %>"><%= message %></div>
    <% end %>
<% end %>

app/views/shared/_navigation.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <%= link_to root_path, class: 'logo' do %>
        <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo Image">
    <% end %>>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <% if user_signed_in? %>
        <nav role="navigation">
          <ul id="js-navigation-menu" class="navigation-menu show">
            <li class="nav-link"><%= link_to 'Adonis', adonis_index_path %></li>
            <li class="nav-link"><%= link_to 'Proteus', proteus_index_path %></li>
            <li class="nav-link"><%= link_to t('views.locations.index.title'), locations_path %></li>
            <li class="nav-link"><%= link_to t('views.users.index.title'), users_path %></li>
          </ul>
        </nav>
        <div class="navigation-tools">
          <ul class="navigation-menu show">
            <li class="nav-link"><%= link_to t('views.static_pages.statistics.title'), statistics_path %></li>
            <li class="nav-link"><%= link_to t('views.static_pages.settings.title'), settings_path %></li>
            <li class="nav-link">
            <li class="nav-link more"><%= link_to current_user.name.split(' ').first %>
              <ul class="submenu">
                <li><%= link_to 'Change settings', edit_user_registration_path %></li>
                <li>
                  <%= link_to t('views.application.buttons.sign_out'), destroy_user_session_path, method: :delete %>
                </li>
              </ul>
            </li>
            </li>
          </ul>
        </div>
    <% else %>
        <div class="navigation-tools">
          <ul class="navigation-menu show">
            <li class="nav-link"><%= link_to t('views.application.buttons.sign_in'), new_user_session_path %></li>
          </ul>
        </div>
    <% end %>
  </div>
</header>